### ISSUE TITLE
可以给一个去掉独显和wifi的efi吗，想安装osx11.6

### ISSUE THREAD

**Issue by gosocn** [vickeyrao/Opencore-for-Dell-Vostro-3900#1]
可以给一个去掉独显和wifi的efi吗，想安装osx11.6，谢谢

**Comment by vickeyrao** [comment]
抱歉我已经很久没有使用这台电脑了，如果你会使用 ProperTree 的话，可以按下图注入核显信息
![](https://dortania.github.io/OpenCore-Install-Guide/assets/img/DeviceProperties.a7e57857.png)

删除 OC > Kexts 文件夹里面有关无线网卡的驱动：
- AirportBrcmFixup.kext
- BrcmBluetoothInjector.kext
- BrcmFirmwareData.kext
- BrcmPatchRAM3.kext

之后在 ProperTree 里面点 File - OC Clean Snapshot 选择 OC 文件夹重建 config.plist

**Comment by gosocn** [comment]
谢谢，已经驱动核显了，有需要跳转https://github.com/gosocn/Opencore-for-Dell-Vostro-3900-Mac11.6
